# Singleton service factory configuration/IoC injection
singletons:
- javax.sql.DataSource:
  - com.zaxxer.hikari.HikariDataSource:
      jdbcUrl: jdbc:mysql://localhost:3306/eventuate?useSSL=false
      username: root
      password: rootpassword
      maximumPoolSize: 2
      useServerPrepStmts: true
      cachePrepStmts: true
      cacheCallableStmts: true
      prepStmtCacheSize: 4096
      prepStmtCacheSqlLimit: 2048
- com.networknt.eventuate.jdbc.EventuateSchema: com.networknt.eventuate.cdc.mysql.binlog.MySqlCdcServiceInitializer::eventuateSchema
- com.networknt.eventuate.cdc.mysql.binlog.SourceTableNameSupplier: com.networknt.eventuate.cdc.mysql.binlog.MySqlCdcServiceInitializer::sourceTableNameSupplier
- com.networknt.eventuate.jdbc.EventuateJdbcAccess:
  - com.networknt.eventuate.server.jdbckafkastore.EventuateLocalJdbcAccess
- com.networknt.eventuate.cdc.mysql.binlog.IWriteRowsEventDataParser: com.networknt.eventuate.cdc.mysql.binlog.MySqlCdcServiceInitializer::eventDataParser
- com.networknt.eventuate.cdc.mysql.binlog.MySqlBinaryLogClient: com.networknt.eventuate.cdc.mysql.binlog.MySqlCdcServiceInitializer::mySqlBinaryLogClient
- com.networknt.eventuate.kafka.producer.EventuateKafkaProducer: com.networknt.eventuate.cdc.mysql.binlog.MySqlCdcServiceInitializer::eventuateKafkaProducer
- com.networknt.eventuate.cdc.mysql.binlog.DatabaseBinlogOffsetKafkaStore: com.networknt.eventuate.cdc.mysql.binlog.MySqlCdcServiceInitializer::binlogOffsetKafkaStore
- com.networknt.eventuate.cdc.mysql.binlog.DebeziumBinlogOffsetKafkaStore: com.networknt.eventuate.cdc.mysql.binlog.MySqlCdcServiceInitializer::debeziumBinlogOffsetKafkaStore
- com.networknt.eventuate.server.common.PublishingStrategy:
  - com.networknt.eventuate.server.common.PublishedEventPublishingStrategy
- com.networknt.eventuate.server.common.CdcProcessor: com.networknt.eventuate.cdc.mysql.binlog.MySqlCdcServiceInitializer::mySQLCdcProcessor
- com.networknt.eventuate.server.common.CdcKafkaPublisher: com.networknt.eventuate.cdc.mysql.binlog.MySqlCdcServiceInitializer::mySQLCdcKafkaPublisher
- org.apache.curator.framework.CuratorFramework: com.networknt.eventuate.cdc.mysql.binlog.MySqlCdcServiceInitializer::curatorFramework
- com.networknt.eventuate.server.common.EventTableChangesToAggregateTopicTranslator: com.networknt.eventuate.cdc.mysql.binlog.MySqlCdcServiceInitializer::mySqlEventTableChangesToAggregateTopicTranslator
# HandlerProvider implementation
- com.networknt.server.HandlerProvider:
  - com.networknt.eventuate.cdc.server.CdcServer
# StartupHookProvider implementations, there are one to many and they are called in the same sequence defined.
- com.networknt.server.StartupHookProvider:
  - com.networknt.eventuate.cdc.server.CdcServerStartupHookProvider
# ShutdownHookProvider implementations, there are one to many and they are called in the same sequence defined.
- com.networknt.server.ShutdownHookProvider:
  - com.networknt.eventuate.cdc.server.CdcServerShutdownHookProvider
# MiddlewareHandler implementations, the calling sequence is as defined in the request/response chain.
